return {
  -- {
  --   "MeanderingProgrammer/render-markdown.nvim",
  --   -- dependencies = { "nvim-treesitter/nvim-treesitter", "echasnovski/mini.nvim" }, -- if you use the mini.nvim suite
  --   -- dependencies = { 'nvim-treesitter/nvim-treesitter', 'echasnovski/mini.icons' }, -- if you use standalone mini plugins
  --   dependencies = { 'nvim-treesitter/nvim-treesitter', 'nvim-tree/nvim-web-devicons' }, -- if you prefer nvim-web-devicons
  --   ---@module 'render-markdown'
  --   ---@type render.md.UserConfig
  --   opts = {},
  -- },
  -- {
  --   "OXY2DEV/markview.nvim",
  --   lazy = false,
  --   dependencies = {
  --     "nvim-treesitter/nvim-treesitter",
  --     "nvim-tree/nvim-web-devicons",
  --   },
  --   -- opts = function()
  --   --   local presets = require("markview.presets")
  --   --   return {
  --   --     preview = {
  --   --       hybrid_modes = { "n" },
  --   --     },
  --   --     checkboxes = presets.checkboxes.nerd,
  --   --   }
  --   -- end,
  -- },
}
